import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Layout from "../components/Layout";

const Page = () => {
  const router = useRouter();
  return (
    <div>
      ajkshdfkjasjkkfhaskjdfkasjbdckjasdnckjsdcjnsdkjaskjdcakjsdckjasckjasndckjasndckjasndckjasndckjadcjdkjnaskjdcaksjdckajsdnckjasndckasjckjasndckjasdndckjasndckajsddnckajsdnckjasdndckjasdckjasdcasjcjasndckjasdckjndknasdkjcaksjddckajsckjasckjasckjasdcjasckjasckjasdckjnasdkjnaskjdcaksjnckajsddnckjasdckjasdckjasddckjasddnckasjdckajsdnckasjddckjasdckjasdnckjasddckjasdckjasndckjasddckjasndckjjsadnkajkshdfkjasjkkfhaskjdfkasjbdckjasdnckjsdcjnsdkjaskjdcakjsdckjasckjasndckjasndckjasndckjasndckjadcjdkjnaskjdcaksjdckajsdnckjasndckasjckjasndckjasdndckjasndckajsddnckajsdnckjasdndckjasdckjasdcasjcjasndckjasdckjndknasdkjcaksjddckajsckjasckjasckjasdcjasckjasckjasdckjnasdkjnaskjdcaksjnckajsddnckjasdckjasdckjasddckjasddnckasjdckajsdnckasjddckjasdckjasdnckjasddckjasdckjasndckjasddckjasndckjjsadnkajkshdfkjasjkkfhaskjdfkasjbdckjasdnckjsdcjnsdkjaskjdcakjsdckjasckjasndckjasndckjasndckjasndckjadcjdkjnaskjdcaksjdckajsdnckjasndckasjckjasndckjasdndckjasndckajsddnckajsdnckjasdndckjasdckjasdcasjcjasndckjasdckjndknasdkjcaksjddckajsckjasckjasckjasdcjasckjasckjasdckjnasdkjnaskjdcaksjnckajsddnckjasdckjasdckjasddckjasddnckasjdckajsdnckasjddckjasdckjasdnckjasddckjasdckjasndckjasddckjasndckjjsadnkajkshdfkjasjkkfhaskjdfkasjbdckjasdnckjsdcjnsdkjaskjdcakjsdckjasckjasndckjasndckjasndckjasndckjadcjdkjnaskjdcaksjdckajsdnckjasndckasjckjasndckjasdndckjasndckajsddnckajsdnckjasdndckjasdckjasdcasjcjasndckjasdckjndknasdkjcaksjddckajsckjasckjasckjasdcjasckjasckjasdckjnasdkjnaskjdcaksjnckajsddnckjasdckjasdckjasddckjasddnckasjdckajsdnckasjddckjasdckjasdnckjasddckjasdckjasndckjasddckjasndckjjsadnk
    </div>
  );
};

export default Page;
